name: backend

type: "nodejs:20"

mounts:
  "web/uploads":
    source: local
    source_path: uploads

disk: 2048

variables:
  env:
    NODE_ENV: "production"
    DATABASE_URL: "postgres://main:main@postgresql.internal:5432/main"
    MONGO_URL: "mongodb://main:main@mongodb.internal:27017/main"
    GMAIL_USER: "julupeervinyle@gmail.com"
    GMAIL_PASS: "vjgtuxkztiqwuiqh"
    EMAIL_FROM: "julupeervinyle@gmail.com"
    DOMAINE_URL: "www.juluandpeer.store"
    LOCAl_URL: "http://localhost:8080/resetPassword"
    JWT_EXPIRES_IN: 400000
    JWT_SECRET: "998c2614eb0acf4eea946414667e78598e286a6c6b3911602f8b23a76811196b"
    STRIPE_SECRET: "sk_test_51LPNAtJ14Llo270Puu3F1bzWiTxuAhW535pVkMKIiJe07me0Q2sOawgQwN4H2OKBJInr1NhdqGbUIpSmaiBYlLaa00cud191SX"
    STRIPE_LOCAL_WH_TOKEN: "whsec_fb91ca888a8d3b410eb9019268979b4b86f84067fe9a7f2f91016ecac79d8617"
    STRIPE_PROD_WH_TOKEN: "whsec_SgM6k1L43sUxHx7zRCekVdh0E6CKdLvY"

# relationships:
#   mongodb: "mongodb:mongodb"
#   postgresql: "postgresql:postgresql"

hooks:
  build: |
    npm install -g sequelize sequelize-cli
  deploy: |
    echo "Running migrations..."
    sequelize-cli db:migrate --env production
    echo "Undoing all seeds..."
    sequelize-cli db:seed:undo:all --env production
    echo "Seeding the database..."
    sequelize-cli db:seed:all --env production

web:
  commands:
    start: "node server.js"
